apiVersion: v1
kind: Namespace
metadata:
  name: nginx-text
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-text-deploy
  namespace: nginx-text
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-text
  template:
    metadata:
      labels:
        app: nginx-text
    spec:
      containers:
      - name: nginx-text
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-text-svc
  namespace: nginx-text
  labels:
    app: nginx-text
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  8083
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-text
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-text-ingress
  namespace: nginx-test
spec:
  rules:
 - host: "nginx-text.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-test-svc 
            port:
              number: 80
