apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  labels:
    app: awx-operator
    cluster: in-cluster
    project: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://ansible.github.io/awx-operator/
    chart: awx-operator
    targetRevision: "1.1.0"
    helm:
      values: |
        AWX:
          enabled: true
          name: awx
          spec:
            service_type: LoadBalancer
            loadbalancer_protocol: https
            loadbalancer_port: 8052
            admin_user: admin
            ingress_type: ingress
            ingress_class_name: nginx
            hostname: awx.keshikslab.com
            ingress_tls_secret: awx-server-tls
            task_extra_env: |
              - name: "NETBOX_TOKEN"
                valueFrom:
                  secretKeyRef:
                    name: awx-tokens
                    key: netbox-token
                    
              - name: "NETBOX_API"
                value: "SOMETHING"

  destination:
    server: https://kubernetes.default.svc
    namespace: awx
