apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  labels:
    app: awx-operator
    cluster: in-cluster
    project: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://ansible.github.io/awx-operator/
    chart: awx-operator
    targetRevision: "1.1.3"
    helm:
      values: |
        AWX:
          enabled: true
          name: awx
          spec:
            ipv6_disabled: true
            service_type: LoadBalancer
            admin_user: admin
            ingress_type: ingress
            hostname: awx.keshikslab.com
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
