apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  labels:
    app: awx-operator
    cluster: in-cluster
    project: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://ansible.github.io/awx-operator/
    chart: awx-operator
    targetRevision: "1.1.0"
    helm:
      values: |
        apiVersion: awx.ansible.com/v1beta1
        kind: AWX
        metadata:
          name: example-awx
        spec:
          ee_resource_requirements:
            requests:
              cpu: 50m
              memory: 64M
          task_resource_requirements:
            requests:
              cpu: 50m
              memory: 128M
          web_resource_requirements:
            requests:
              cpu: 50m
              memory: 128M
            
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
