apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
  labels:
    app: awx-operator
    cluster: in-cluster
    project: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://ansible.github.io/awx-operator/
    chart: awx-operator
    targetRevision: "1.1.0"
    helm:
      values: |
        AWX:
          enabled: true
          name: awx
          spec:
            admin_user: admin
            service_type: LoadBalancer
            loadbalancer_protocol: https
            loadbalancer_port: 8443
            service_annotations: |
              environment: prod
            service_labels: |
              environment: prod
            ingress_type: ingress
            ingress_annotations: |
              environment: prod
            hostname: awx.example.com
            task_extra_env: |
              - name: "GITLAB_TOKEN"
                valueFrom:
                  secretKeyRef:
                    name: awx-tokens
                    key: gitlab-token

              - name: "NETBOX_TOKEN"
                valueFrom:
                  secretKeyRef:
                    name: awx-tokens
                    key: netbox-token

            extra_volumes: |
              - name: awx-sshkey-volume
                secret:
                  secretName: awx-sshkey
                  defaultMode: 0400
            
            task_extra_volume_mounts: |
              - name: awx-sshkey-volume
                mountPath: /var/lib/awx/.ssh/id_rsa
                subPath: awx-sshkey
                

  destination:
    server: https://kubernetes.default.svc
    namespace: awx
