apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-tokens
  labels:
    app: awx-tokens
    cluster: in-cluster
    project: default
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kiwigrid.github.io
    chart: any-resource
    targetRevision: "0.1.0"
    helm:
      values: |
        anyResources:
          awx-namespace: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              name: awx
          secret-store: |-
            apiVersion: external-secrets.io/v1beta1
            kind: ClusterSecretStore
            metadata:
              name: gcp-secret-store
              namespace: cluster-store
            spec:
              provider:
                  gcpsm:                                                  
                    auth:
                      secretRef:
                        secretAccessKeySecretRef:
                          name: gcpsm-secret                        
                          key: secret-access-credentials
                    projectID: fast-chess-362509
          awx-tokens: |-
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: awx-external-tokens
              namespace: awx
            spec:
              secretStoreRef:
                kind: SecretStore
                name: gcp-secret-store
                namespace: default
              target:
                name: awx-tokens
                creationPolicy: Owner
              data:
                - secretKey: "netbox-token"
                  remoteRef:
                    key: awx
                    version: latest
                    property: NETBOX_TOKEN

                - secretKey: "gitlab-token"
                  remoteRef:
                    key: awx
                    version: latest
                    property: GITLAB_TOKEN
                      
          awx-sshkey: |-
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: awx-external-sshkey
              namespace: awx
            spec:
              secretStoreRef:
                kind: SecretStore
                name: gcp-secret-store
                namespace: default
              target:
                name: awx-sshkey
                creationPolicy: Owner
              data:
                - secretKey: awx-sshkey
                  remoteRef:
                    key: awxsshkey
                    version: latest
                    
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
