apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-tokens
  labels:
    app: awx-tokens
    cluster: cluster-2
    project: default
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kiwigrid.github.io
    chart: any-resource
    targetRevision: "0.1.0"
    helm:
      values: |
        anyResources:
          awx-tokens: |-
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: awx-external-tokens
              namespace: awx
            spec:
              secretStoreRef:
                kind: ClusterSecretStore
                name: gcp-secret-store
              target:
                name: awx-tokens
                creationPolicy: Owner
              data:
                - secretKey: "netbox-token"
                  remoteRef:
                    key: awx
                    version: latest
                    property: NETBOX_TOKEN

                - secretKey: "gitlab-token"
                  remoteRef:
                    key: awx
                    version: latest
                    property: GITLAB_TOKEN
                    
          awx-sshkey: |-
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: awx-external-sshkey
              namespace: awx
            spec:
              secretStoreRef:
                kind: ClusterSecretStore
                name: gcp-secret-store
              target:
                name: awx-sshkey
                creationPolicy: Owner
              data:
                - secretKey: awx-sshkey
                  remoteRef:
                    key: awxsshkey
                    version: latest

  destination:
    name: docker-desktop
    namespace: awx

