apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: argocd
spec:
  dnsNames:
    - keshikslab.com
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer