apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # appprotect.f5.com/app-protect-policy: "false"
    # nginx.org/hsts-behind-proxy: "true"
    # nginx.org/redirect-to-https: "true"
    # nginx.org/hsts-include-subdomains: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  labels:
  name: argocd-ingress
  namespace: argocd
spec:
  ingressClassName: traefik-external
  rules:
    - host: argocd.keshikslab.com
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - argocd.keshikslab.com
      secretName: letsencrypt-staging-tls