apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  commonName: "*.${MY_DOMAIN}"
  dnsNames:
    - "${MY_DOMAIN}"
    - "*.${MY_DOMAIN}"
  secretName: letsencrypt-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
