apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - keshikslabs.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: selfsigned