apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  commonName: "*.keshikslab.com"
  dnsNames:
    - "keshikslab.com"
    - "*.keshikslab.com"
  secretName: letsencrypt-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer